
classdef CentroidalState < ros.Message
    %CentroidalState MATLAB implementation of whole_body_state_msgs/CentroidalState
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'whole_body_state_msgs/CentroidalState' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '23ae41306b44b6e3e1e14f56a5849ac7' % The MD5 Checksum of the message definition
        PropertyList = { 'ComPosition' 'ComVelocity' 'BaseOrientation' 'BaseAngularVelocity' 'Momenta' 'MomentaRate' } % List of non-constant message properties
        ROSPropertyList = { 'com_position' 'com_velocity' 'base_orientation' 'base_angular_velocity' 'momenta' 'momenta_rate' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msg.geometry_msgs.Quaternion' ...
            'ros.msggen.geometry_msgs.Vector3' ...
            'ros.msggen.geometry_msgs.Twist' ...
            'ros.msggen.geometry_msgs.Twist' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ComPosition
        ComVelocity
        BaseOrientation
        BaseAngularVelocity
        Momenta
        MomentaRate
    end
    methods
        function set.ComPosition(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'CentroidalState', 'ComPosition')
            obj.ComPosition = val;
        end
        function set.ComVelocity(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'CentroidalState', 'ComVelocity')
            obj.ComVelocity = val;
        end
        function set.BaseOrientation(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msg.geometry_msgs.Quaternion'};
            validateattributes(val, validClasses, validAttributes, 'CentroidalState', 'BaseOrientation')
            obj.BaseOrientation = val;
        end
        function set.BaseAngularVelocity(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Vector3'};
            validateattributes(val, validClasses, validAttributes, 'CentroidalState', 'BaseAngularVelocity')
            obj.BaseAngularVelocity = val;
        end
        function set.Momenta(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Twist'};
            validateattributes(val, validClasses, validAttributes, 'CentroidalState', 'Momenta')
            obj.Momenta = val;
        end
        function set.MomentaRate(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Twist'};
            validateattributes(val, validClasses, validAttributes, 'CentroidalState', 'MomentaRate')
            obj.MomentaRate = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.whole_body_state_msgs.CentroidalState.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.whole_body_state_msgs.CentroidalState(strObj);
        end
    end
end
