
classdef RhonnState < ros.Message
    %RhonnState MATLAB implementation of whole_body_state_msgs/RhonnState
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'whole_body_state_msgs/RhonnState' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'cab5c60dc61b925dabf32ac8cc684551' % The MD5 Checksum of the message definition
        PropertyList = { 'Name' 'Position' 'Velocity' 'ErrorW1' 'ErrorW2' 'ObsPosition' 'ObsVelocity' 'Reference' } % List of non-constant message properties
        ROSPropertyList = { 'name' 'position' 'velocity' 'error_w1' 'error_w2' 'obs_position' 'obs_velocity' 'reference' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Name
        Position
        Velocity
        ErrorW1
        ErrorW2
        ObsPosition
        ObsVelocity
        Reference
    end
    methods
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'Name');
            obj.Name = char(val);
        end
        function set.Position(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'Position');
            obj.Position = double(val);
        end
        function set.Velocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'Velocity');
            obj.Velocity = double(val);
        end
        function set.ErrorW1(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'ErrorW1');
            obj.ErrorW1 = double(val);
        end
        function set.ErrorW2(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'ErrorW2');
            obj.ErrorW2 = double(val);
        end
        function set.ObsPosition(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'ObsPosition');
            obj.ObsPosition = double(val);
        end
        function set.ObsVelocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'ObsVelocity');
            obj.ObsVelocity = double(val);
        end
        function set.Reference(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'RhonnState', 'Reference');
            obj.Reference = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.whole_body_state_msgs.RhonnState.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.whole_body_state_msgs.RhonnState(strObj);
        end
    end
end
