
classdef JoyPriorityAction < ros.Message
    %JoyPriorityAction MATLAB implementation of twist_mux_msgs/JoyPriorityAction
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'twist_mux_msgs/JoyPriorityAction' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'd5a016b49f278075666fbc901debbd08' % The MD5 Checksum of the message definition
        PropertyList = { 'ActionGoal' 'ActionResult' 'ActionFeedback' } % List of non-constant message properties
        ROSPropertyList = { 'action_goal' 'action_result' 'action_feedback' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.twist_mux_msgs.JoyPriorityActionGoal' ...
            'ros.msggen.twist_mux_msgs.JoyPriorityActionResult' ...
            'ros.msggen.twist_mux_msgs.JoyPriorityActionFeedback' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ActionGoal
        ActionResult
        ActionFeedback
    end
    methods
        function set.ActionGoal(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.twist_mux_msgs.JoyPriorityActionGoal'};
            validateattributes(val, validClasses, validAttributes, 'JoyPriorityAction', 'ActionGoal')
            obj.ActionGoal = val;
        end
        function set.ActionResult(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.twist_mux_msgs.JoyPriorityActionResult'};
            validateattributes(val, validClasses, validAttributes, 'JoyPriorityAction', 'ActionResult')
            obj.ActionResult = val;
        end
        function set.ActionFeedback(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.twist_mux_msgs.JoyPriorityActionFeedback'};
            validateattributes(val, validClasses, validAttributes, 'JoyPriorityAction', 'ActionFeedback')
            obj.ActionFeedback = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.twist_mux_msgs.JoyPriorityAction.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.twist_mux_msgs.JoyPriorityAction(strObj);
        end
    end
end
