
classdef Subscription < ros.Message
    %Subscription MATLAB implementation of tf_lookup/Subscription
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tf_lookup/Subscription' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2f26b645cf5988fb447dd948d42f673d' % The MD5 Checksum of the message definition
        PropertyList = { 'Target' 'Source' } % List of non-constant message properties
        ROSPropertyList = { 'target' 'source' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Target
        Source
    end
    methods
        function set.Target(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'Subscription', 'Target');
            obj.Target = char(val);
        end
        function set.Source(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'Subscription', 'Source');
            obj.Source = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tf_lookup.Subscription.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tf_lookup.Subscription(strObj);
        end
    end
end
