
classdef TfStreamAction < ros.Message
    %TfStreamAction MATLAB implementation of tf_lookup/TfStreamAction
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tf_lookup/TfStreamAction' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'eada82f97831269824585b87423d0c8f' % The MD5 Checksum of the message definition
        PropertyList = { 'ActionGoal' 'ActionResult' 'ActionFeedback' } % List of non-constant message properties
        ROSPropertyList = { 'action_goal' 'action_result' 'action_feedback' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.tf_lookup.TfStreamActionGoal' ...
            'ros.msggen.tf_lookup.TfStreamActionResult' ...
            'ros.msggen.tf_lookup.TfStreamActionFeedback' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        ActionGoal
        ActionResult
        ActionFeedback
    end
    methods
        function set.ActionGoal(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.tf_lookup.TfStreamActionGoal'};
            validateattributes(val, validClasses, validAttributes, 'TfStreamAction', 'ActionGoal')
            obj.ActionGoal = val;
        end
        function set.ActionResult(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.tf_lookup.TfStreamActionResult'};
            validateattributes(val, validClasses, validAttributes, 'TfStreamAction', 'ActionResult')
            obj.ActionResult = val;
        end
        function set.ActionFeedback(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.tf_lookup.TfStreamActionFeedback'};
            validateattributes(val, validClasses, validAttributes, 'TfStreamAction', 'ActionFeedback')
            obj.ActionFeedback = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tf_lookup.TfStreamAction.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tf_lookup.TfStreamAction(strObj);
        end
    end
end
