
classdef JointCommand < ros.Message
    %JointCommand MATLAB implementation of whole_body_state_msgs/JointCommand
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'whole_body_state_msgs/JointCommand' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '7b9bd29f162ce43dcd78df2226b6f95d' % The MD5 Checksum of the message definition
        PropertyList = { 'Name' 'Total' 'Feedforward' 'Feedback' } % List of non-constant message properties
        ROSPropertyList = { 'name' 'total' 'feedforward' 'feedback' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Name
        Total
        Feedforward
        Feedback
    end
    methods
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Name');
            obj.Name = char(val);
        end
        function set.Total(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Total');
            obj.Total = double(val);
        end
        function set.Feedforward(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Feedforward');
            obj.Feedforward = double(val);
        end
        function set.Feedback(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'JointCommand', 'Feedback');
            obj.Feedback = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.whole_body_state_msgs.JointCommand.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.whole_body_state_msgs.JointCommand(strObj);
        end
    end
end
