
classdef Rhonn < ros.Message
    %Rhonn MATLAB implementation of whole_body_state_msgs/Rhonn
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'whole_body_state_msgs/Rhonn' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2f2e10869d748da4cbaa5fbe0d27146b' % The MD5 Checksum of the message definition
        PropertyList = { 'Name' 'Position' 'Velocity' 'ErrorW1' 'ErrorW2' 'Effort' } % List of non-constant message properties
        ROSPropertyList = { 'name' 'position' 'velocity' 'error_w1' 'error_w2' 'effort' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Name
        Position
        Velocity
        ErrorW1
        ErrorW2
        Effort
    end
    methods
        function set.Name(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'Rhonn', 'Name');
            obj.Name = char(val);
        end
        function set.Position(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Rhonn', 'Position');
            obj.Position = double(val);
        end
        function set.Velocity(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Rhonn', 'Velocity');
            obj.Velocity = double(val);
        end
        function set.ErrorW1(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Rhonn', 'ErrorW1');
            obj.ErrorW1 = double(val);
        end
        function set.ErrorW2(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Rhonn', 'ErrorW2');
            obj.ErrorW2 = double(val);
        end
        function set.Effort(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'Rhonn', 'Effort');
            obj.Effort = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.whole_body_state_msgs.Rhonn.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.whole_body_state_msgs.Rhonn(strObj);
        end
    end
end
