// Generated by gencpp from file whole_body_state_msgs/JointCommand.msg
// DO NOT EDIT!


#ifndef WHOLE_BODY_STATE_MSGS_MESSAGE_JOINTCOMMAND_H
#define WHOLE_BODY_STATE_MSGS_MESSAGE_JOINTCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace whole_body_state_msgs
{
template <class ContainerAllocator>
struct JointCommand_
{
  typedef JointCommand_<ContainerAllocator> Type;

  JointCommand_()
    : name()
    , total(0.0)
    , feedforward(0.0)
    , feedback(0.0)  {
    }
  JointCommand_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , total(0.0)
    , feedforward(0.0)
    , feedback(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef double _total_type;
  _total_type total;

   typedef double _feedforward_type;
  _feedforward_type feedforward;

   typedef double _feedback_type;
  _feedback_type feedback;





  typedef boost::shared_ptr< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> const> ConstPtr;

}; // struct JointCommand_

typedef ::whole_body_state_msgs::JointCommand_<std::allocator<void> > JointCommand;

typedef boost::shared_ptr< ::whole_body_state_msgs::JointCommand > JointCommandPtr;
typedef boost::shared_ptr< ::whole_body_state_msgs::JointCommand const> JointCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::whole_body_state_msgs::JointCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace whole_body_state_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/home/abdiel/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/geometry_msgs/cmake/../msg'], 'whole_body_state_msgs': ['/home/abdiel/catkin_ws/src/matlab_msg_gen_ros1/glnxa64/src/whole_body_state_msgs/msg'], 'std_msgs': ['/home/abdiel/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg', '/home/abdiel/MATLAB/R2021b/sys/ros1/glnxa64/ros1/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b9bd29f162ce43dcd78df2226b6f95d";
  }

  static const char* value(const ::whole_body_state_msgs::JointCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b9bd29f162ce43dULL;
  static const uint64_t static_value2 = 0xcd78df2226b6f95dULL;
};

template<class ContainerAllocator>
struct DataType< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "whole_body_state_msgs/JointCommand";
  }

  static const char* value(const ::whole_body_state_msgs::JointCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message describes the state of joint command.\n"
"#\n"
"# The state of each command (revolute or prismatic) is defined by:\n"
"#  * the total command to the joint (Nm or N),\n"
"#  * the feedforward command component (Nm or N), and\n"
"#  * the feedback command component (Nm or N) \n"
"#\n"
"# Each commanded joint is uniquely identified by its name\n"
"\n"
"\n"
"string name\n"
"float64 total\n"
"float64 feedforward\n"
"float64 feedback\n"
;
  }

  static const char* value(const ::whole_body_state_msgs::JointCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.total);
      stream.next(m.feedforward);
      stream.next(m.feedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::whole_body_state_msgs::JointCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::whole_body_state_msgs::JointCommand_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "total: ";
    Printer<double>::stream(s, indent + "  ", v.total);
    s << indent << "feedforward: ";
    Printer<double>::stream(s, indent + "  ", v.feedforward);
    s << indent << "feedback: ";
    Printer<double>::stream(s, indent + "  ", v.feedback);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WHOLE_BODY_STATE_MSGS_MESSAGE_JOINTCOMMAND_H
